spring:
  application:
    name: nacos-discovery-gateway-server
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        metadata:
          name: lengleng
    gateway:
      routes:
        - id: nacos-discovery-provider
          uri: lb://nacos-discovery-provider
          predicates:
            - Path=/provider/**
          filters:
            - StripPrefix=1
      discovery:
        locator:
          lower-case-service-id: true
          enabled: true
#        - id: websocket-server
#          #uri: ws://localhost:8041
#          uri: lb://websocket-server
#          predicates:
#            - Path=/test-ws/**

server:
  port: 8054


